backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home Page"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "banner", name: "banner", widget: "string"}
        - { label: "banner_button_1_Text", name: "banner_button_1_Text", widget: "string"}
        - { label: "banner_button_1_link", name: "banner_button_1_link", widget: "string"}
        - { label: "banner_button_2_Text", name: "banner_button_2_Text", widget: "string"}
        - { label: "banner_youtubevideoId", name: "banner_youtubevideoId", widget: "string"}
        - { label: "our_works_text", name: "our_works_text", widget: "string"}
    - label: "About Page"
      name: "about"
      file: "content/about.md"
      fields:
        - { label: "about_text", name: "about_text", widget: "string"}